name = "moviepluscloudflare"

[build]
command = "" # No build step needed
cwd = "." # Current working directory
output_dir = "." # Static files are in the root directory

pages_build_output_dir = "./" 